---
- name: Staging server deployment
  hosts: stageserver
  become_user: root
  become: true
  vars:
    repo_path: nrbaskar/wilfred_nodejs:{{DOCKER_TAG}}
    dest_path: /home/ec2-user/{{DOCKER_TAG}}
  tasks:
    # Install python pip
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    # Install docker
    - name: Docker installation
      yum:
        name: docker
        state: present
    # Start the docker service
    - name: Docker service start
      service:
        name: docker
        state: started
        enabled: yes
    # install docker python packages
    - name: install docker-py python packages
      pip:
        name: docker-py
        state: present
    # Create directory
    - name: create directory
      file:
        state: directory
        dest: "{{ dest_path }}"
    # Copy Files
    - name: Copy website to hosts
      copy:
        src: ./
        dest: "{{ dest_path }}"
    # Install Nodejs library
    # using multiple shell modules
    - name: Install Nodejs and ExpressJS
      shell: 'curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -'
    # If other package are required mention the package name in "name"
    # e.g : ngix,curl,wget,apache2,nodejs
    - name: install required packages
      yum:
        name: nodejs
        state: present
    - name: Install express JS
      command: sudo npm install express
    # Install all necessary node modules for the project
    # using 'npm'
    - name: Install project dependencies
      command: npm install
      args:
        chdir: "{{ dest_path }}"
    # Install Forever tool
    # This tool is used to run the Node server in background
    # and keep tracking of running process
    - name: Install PM2
      npm: name=pm2 global=yes state=present
    # is already running and avoids restarting service on playbook
    # execution
    - name: Get Forever's list of running processes
      command: pm2 status
      register: pm2_status
      changed_when: false
    # Start the nodeserver using Forever tool
    # the when clause identifies if the server is already	
    # running If so this task is skipped
    - name: Kill pm2 service
      command: pm2 kill
    - name: Start service
      command: pm2 start index.js --name "{{DOCKER_TAG}}-Service"
      args:
        chdir: "{{ dest_path }}"
